loani-fl/Clinitek

resources/views/medicos/create.blade.php
Barra de navegacion estatita y con logo a la par de "Clinitek"
=> Barra de navegacion estatita y con logo

app/Http/Controllers/ConsultaController.php, app/Http/Controllers/PacienteController.php, database/migrations/2025_06_24_043710_add_sexo_to_consultas_table.php, resources/views/consultas/create.blade.php, resources/views/empleado/index.blade.php, resources/views/empleado/show.blade.php, resources/views/welcome.blade.php
Agregar la imagen de fondo a los formularios
agregar logo a la barra de navegación
=> Agregar fondo a los formularios y barra de navegacion con logo

app/Http/Controllers/ConsultaController.php, app/Models/Consulta.php, database/migrations/2025_06_26_194948_add_genero_to_consultas_table.php, database/migrations/2025_06_26_195237_drop_sexo_from_consultas_table.php, resources/views/consultas/create.blade.php
Actualizando el error de genero
=> Corriguiendo errores de campo genero

resources/views/consultas/create.blade.php
=> Corrigiendo detalles

resources/views/consultas/create.blade.php
=> Corrigiendo create

app/Http/Controllers/EmpleadosController.php, resources/views/consultas/create.blade.php
=> agregando foto al show

app/Http/Controllers/ConsultaController.php, app/Models/Consulta.php, database/migrations/2025_06_22_235723_create_consultas_table.php, resources/views/consultas/create.blade.php, resources/views/empleado/show.blade.php
=> delimitando campos

resources/views/empleado/index.blade.php
=> Agregando paginacion

resources/views/consultas/create.blade.php
=> Cambios en consulta

app/Http/Controllers/ConsultaController.php, app/Http/Controllers/PacienteController.php, app/Http/Controllers/PuestoController.php, resources/views/consultas/edit.blade.php, resources/views/pacientes/index.blade.php, resources/views/pacientes/partials/tabla.blade.php, resources/views/puestos/create.blade.php, resources/views/puestos/edit.blade.php, resources/views/puestos/index.blade.php, resources/views/puestos/partials/tabla.blade.php, resources/views/puestos/show.blade.php
Se hizo que el filtro sea dinámico que haga búsqueda sobre todas las paginaciones, se cambiaron estilos a puestos también se le agrego filtro y se modifico el botón de cancelar.
=> Cambios en controladores y vistas para consultas, pacientes y puestos

app/Http/Controllers/ConsultaController.php, app/Http/Controllers/EmpleadosController.php, resources/views/consultas/create.blade.php, resources/views/empleado/index.blade.php
=> Actualizando vistas

app/Http/Controllers/EmpleadosController.php
=> Actualizando

app/Http/Controllers/ConsultaController.php, app/Http/Controllers/DiagnosticoController.php, app/Models/Consulta.php, app/Models/Diagnostico.php, resources/views/Diagnosticos/create.blade.php, resources/views/Diagnosticos/edit.blade.php, resources/views/Diagnosticos/show.blade.php, resources/views/consultas/show.blade.php, routes/web.php
Creando vista edit y show de diagnosticos
=> Creando vista edit y show de diagnosticos

resources/views/consultas/index.blade.php, resources/views/layouts/app.blade.php, resources/views/medicos/create.blade.php
=> Actualizando barra

app/Http/Controllers/PacienteController.php, resources/views/Recetas/show.blade.php, resources/views/pacientes/create.blade.php, resources/views/pacientes/show.blade.php
cambios de pacientes y barras de navegacion
=> cambios de pacientes y barras de navegacion

app/Http/Controllers/ExamenController.php, app/Models/Consulta.php, app/Models/Examen.php, resources/views/Diagnosticos/show.blade.php
Corrigiendo controlador, modelo de examen
=> Corrigiendo controlador, modelo de examen

app/Http/Controllers/ConsultaController.php, resources/views/pacientes/show.blade.php
=> Corrigiendo consultas

resources/views/consultas/edit.blade.php
=> Actualizando consulta

app/Http/Controllers/PacienteController.php
=> Faltaba una s al controlador

app/Http/Controllers/RecetaController.php, app/Models/Receta.php, database/migrations/2025_07_15_151613_create_medicamento_receta_table.php
se creo una nueva migracion llamada medicamentos_receta
=> creacion de migracion para que una medicamentos y recetas

database/seeders/DatabaseSeeder.php, database/seeders/MedicamentosSeeder.php
=> medicamentos

app/Http/Controllers/RecetaController.php, resources/views/Recetas/show.blade.php, routes/web.php
=> cambios realizados

resources/views/Diagnosticos/show.blade.php
Corrigiendo vista show diagnostico
=> Corrigiendo vista show diagnostico

app/Http/Controllers/RecetaController.php, resources/views/Recetas/create.blade.php
=> cambios realizados en recetas

app/Http/Controllers/DiagnosticoController.php, resources/views/Diagnosticos/edit.blade.php, resources/views/Diagnosticos/show.blade.php, resources/views/consultas/show.blade.php, resources/views/examenes/show.blade.php
Corrigiendo show diagnostico, agg ver diagnósticos anteriores
=> Corrigiendo show diagnostico

app/Http/Controllers/DiagnosticoController.php, resources/views/Diagnosticos/edit.blade.php, resources/views/Diagnosticos/show.blade.php, resources/views/consultas/index.blade.php, resources/views/empleado/index.blade.php, resources/views/layouts/app.blade.php, resources/views/welcome.blade.php
arreglando validaciones, el botón que redirija correctamente.
agg boton de regitro a los index
=> Corrigiendo edit diagnostico

app/Http/Controllers/FarmaciaController.php, database/migrations/2025_08_01_032812_create_farmacias_table.php, resources/views/farmacias/index.blade.php, resources/views/farmacias/partials/tabla.blade.php, resources/views/farmacias/show.blade.php, resources/views/welcome.blade.php
Eliminando el campo estado del index de farmacia
=> Eliminando el campo estado del index de farmacia

app/Http/Controllers/PagoController.php, resources/views/pago/create.blade.php
Actualizando pago create y controlador
=> Actualizando pago create y controlador

resources/views/farmacias/index.blade.php, resources/views/farmacias/partials/tabla.blade.php
Actualizando vista index farmacias
=> Actualizando vista index farmacias

app/Http/Controllers/ConsultaController.php, app/Http/Controllers/DiagnosticoController.php, app/Http/Controllers/RecetaController.php, resources/views/Recetas/create.blade.php
Actualizando vistas recetas, controlador
=> Actualizando vistas recetas, controlador

app/Http/Controllers/PagoController.php, database/migrations/2025_08_06_175844_create_rayosx_order_examenes_table.php, database/migrations/2025_08_09_140644_add_servicio_descripcion_to_pagos_table.php, resources/views/pago/create.blade.php, resources/views/pago/show.blade.php
=> funcionalidad de pago

resources/views/farmacias/show.blade.php
Quitando el boton de buscar en google de show farmacias
=> Quitando el boton de buscar en google de show farmacias

resources/views/rayosX/show.blade.php
Actualizando vista show rayosx imagenes
=> Actualizando vista show rayosx imagenes

resources/views/rayosX/show.blade.php
=> Actualizando vista show

app/Http/Controllers/HospitalizacionController.php, app/Http/Controllers/RecetaController.php, app/Models/Emergencia.php, app/Models/Hospitalizacion.php, database/migrations/2025_09_23_125725_create_hospitalizaciones_table.php, resources/views/Hospitalizacion/transferirHospitalizacion.blade.php, resources/views/consultas/index.blade.php, resources/views/emergencias/show.blade.php, routes/web.php
Creacion de formulario para transferir pacientes a hospitalizacion
=> Creacion de formulario para transferir pacientes a hospitalizacion

resources/views/Hospitalizacion/transferirHospitalizacion.blade.php
Actualizando formulario para transferir pacientes a hospitalizacion
=> Actualizando formulario para transferir pacientes a hospitalizacion

resources/views/emergencias/show.blade.php
=> Actualizando show
